// Market data sources with citations
export const MARKET_SOURCES = {
  cloudAI2024: {
    value: 77.0,
    unit: 'billion USD',
    year: 2024,
    label: 'Cloud AI Market',
    source: 'Market Research Reports',
    url: 'https://www.marketresearchfuture.com/reports/cloud-ai-market',
    citation: 'Cloud AI market valued at $77.0B in 2024',
  },
  edgeAI2024: {
    value: 18.3,
    unit: 'billion USD',
    year: 2024,
    label: 'Edge AI Market',
    source: 'Allied Market Research',
    url: 'https://www.alliedmarketresearch.com/edge-ai-market',
    citation: 'Edge AI market size $18.3B in 2024',
  },
  edgeForecast2033: {
    value: 163.0,
    unit: 'billion USD',
    year: 2033,
    label: 'Edge AI Forecast',
    source: 'Allied Market Research',
    url: 'https://www.alliedmarketresearch.com/edge-ai-market',
    citation: 'Edge AI projected to reach $163B by 2033',
  },
  edgeSoftware2024: {
    value: 1.92,
    unit: 'billion USD',
    year: 2024,
    label: 'Edge AI Software',
    source: 'Market.us',
    url: 'https://market.us/report/edge-ai-software-market/',
    citation: 'Edge AI Software market $1.92B in 2024',
  },
  edgeSoftware2030: {
    value: 7.19,
    unit: 'billion USD',
    year: 2030,
    label: 'Edge AI Software Forecast',
    source: 'Market.us',
    url: 'https://market.us/report/edge-ai-software-market/',
    citation: 'Edge AI Software forecast $7.19B by 2030',
  },
  aiRobotics2032: {
    value: 89.6,
    unit: 'billion USD',
    year: 2032,
    label: 'AI Robotics Market',
    source: 'Precedence Research',
    url: 'https://www.precedenceresearch.com/ai-in-robotics-market',
    citation: 'AI Robotics market projected ~$89.6B by 2032',
  },
}

export const STATS_CONFIG = [
  {
    id: 'cloud-ai',
    sourceKey: 'cloudAI2024',
    prefix: '$',
    suffix: 'B',
    description: 'Cloud AI market value in 2024',
    animationDuration: 2000,
  },
  {
    id: 'edge-ai',
    sourceKey: 'edgeAI2024',
    prefix: '$',
    suffix: 'B',
    description: 'Edge AI market size in 2024',
    animationDuration: 2000,
  },
  {
    id: 'edge-forecast',
    sourceKey: 'edgeForecast2033',
    prefix: '$',
    suffix: 'B',
    description: 'Edge AI forecast by 2033',
    animationDuration: 2500,
  },
  {
    id: 'edge-software',
    sourceKey: 'edgeSoftware2024',
    prefix: '$',
    suffix: 'B',
    description: 'Edge AI Software (2024)',
    animationDuration: 1800,
  },
  {
    id: 'edge-software-forecast',
    sourceKey: 'edgeSoftware2030',
    prefix: '$',
    suffix: 'B',
    description: 'Edge AI Software by 2030',
    animationDuration: 1800,
  },
  {
    id: 'ai-robotics',
    sourceKey: 'aiRobotics2032',
    prefix: '~$',
    suffix: 'B',
    description: 'AI Robotics by 2032',
    animationDuration: 2200,
  },
]
